name: CI pipline

on:
  push:
    branches:
      - feature/develop/*
    paths-ignore:
      - '**/*.md'
      - '**/.gitignore'
  pull_request:
    branches:
      - feature
    paths-ignore:
      - '*.md'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      
      - name: Install Arduino CLI
        run: |
          $ArduinoURL = "https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Windows_64bit.zip"
          Invoke-WebRequest -Uri $ArduinoURL -OutFile arduino-cli.zip
          Expand-Archive arduino-cli.zip -DestinationPath .
          echo "${{github.workspace}}" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          .\arduino-cli.exe config init
          .\arduino-cli.exe core update-index
          .\arduino-cli.exe core install arduino:avr
        shell: pwsh
      
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      
      - name: Store Client Build
        uses: actions/upload-artifact@v3
        with:
          name: client-files
          path: deploy/client-output/*
          retention-days: 7
          
      - name: Store Server Build
        uses: actions/upload-artifact@v3
        with:
          name: server-files
          path: deploy/server-output/*
          retention-days: 7